ccnmtl/django_courseaffils

- .gitignore
- CHANGES.txt
- courseaffils/forms.py
- courseaffils/lib.py
- courseaffils/middleware.py
- courseaffils/models.py
- courseaffils/templatetags/coursetags.py
- courseaffils/views.py
- setup.py
> Removing Mediathread only "logged_in.js" view

- courseaffils/lib.py
See:
https://github.com/ccnmtl/django_courseaffils/pull/23#discussion_r55881971
> Simplify User import

- courseaffils/tests/factories.py
- courseaffils/tests/test_models.py
- courseaffils/tests/test_views.py
- courseaffils/views.py
- test_reqs.txt
I ran into this problem on Mediathread.
> Fix an exception that occurs when course has no CourseInfo

- CHANGES.txt
- courseaffils/views.py
- setup.py
To maintain compatibility with the old set_course view.
> Add next_redirect context var to CourseListView

- courseaffils/models.py
I ran into this error on my local mediathread when a Course has no
faculty_group:
> 'NoneType' object has no attribute 'user_set'
Checking if the faculty_group exists before using it resolves the issue.
> Fix error when course has no faculty_group

- courseaffils/columbia.py
- courseaffils/forms.py
- courseaffils/templates/courseaffils/course_form.html
- courseaffils/tests/mixins.py
- courseaffils/tests/test_views.py
- courseaffils/tests/urls.py
- courseaffils/views.py
- test_reqs.txt
This isn't complete yet (there's much more to figure out), but I've
added a basic Course/CourseInfo form.
> Add course creation form (phase 1) - PMT #105457

- courseaffils/lib.py
- courseaffils/tests/test_lib.py
This is for determining whether a User is a faculty member or not.
> Add faculty_courses_for_user function

- courseaffils/middleware.py
This doesn't need to be a nested method.
> Move decorate_request() out of process_request()

- CHANGES.txt
- courseaffils/models.py
- courseaffils/templates/courseaffils/course_row.html
- courseaffils/views.py
- setup.py
* Adding select_related/prefetch_related where appropriate.
* Querying all the request.user's roles in advance to improve rendering (tremendously).
* MeTh previous query hit for "Past Semesters" was 4009. This brings it down to 8. Massive speed increase.
> Optimize CourseListView Rendering

- courseaffils/lib.py
- courseaffils/middleware.py
- courseaffils/migrations/0003_auto_20160429_1353.py
- courseaffils/models.py
- courseaffils/tests/factories.py
- courseaffils/tests/test_models.py
I need to move the Affil model from mediathread to courseaffils in order
to do this.
> Change middleware so faculty always see course list - PMT #105456

- courseaffils/templates/courseaffils/course_row.html
> remove coursetags from course_row.html

- CHANGES.txt
- courseaffils/models.py
- courseaffils/tests/test_models.py
- setup.py
For automatically prepending to the course name in mediathread.
> Add Affil.shortname

- courseaffils/models.py
This will simplify some template logic when displaying affils and courses in the same table in mediathread.
> Add Affil.is_affil = True

- CHANGES.txt
- courseaffils/models.py
- courseaffils/tests/test_models.py
Moving some code here from Mediathread:
https://github.com/ccnmtl/mediathread/blob/master/mediathread/main/util.py#L67
> Add Affil.get_course

- courseaffils/views.py
> replace request.REQUEST with POST and GET

- courseaffils/templatetags/coursetags.py
- courseaffils/tests/test_views.py
- courseaffils/views.py
Returns a list of courses where the user is an instructor
> get_courses_for_instructor

- courseaffils/middleware.py
> middleware: Nested ifs: turn these into boolean ANDs

- .travis.yml
- CHANGES.txt
- courseaffils/columbia.py
- courseaffils/middleware.py
- courseaffils/migrations/0001_initial.py
- courseaffils/migrations/0003_auto_20160429_1353.py
- courseaffils/models.py
- courseaffils/templatetags/coursetags.py
- courseaffils/tests/test_settings.py
- courseaffils/tests/test_views.py
- courseaffils/views.py
- test_reqs.txt
* Add django 2.2 testing, remove django 1.8
* Fix some flake8 regex problems
> Add django 2.2 support, remove django 1.8

- test_reqs.txt
> Pin markdown to 3.1.1

- courseaffils/tests/factories.py
- test_reqs.txt
This requires some changes to the imports:
https://factoryboy.readthedocs.io/en/latest/changelog.html#id2
> :arrow_up: factory_boy 3.0.1

- courseaffils/views.py
* Render to response is deprecated for django3
> Render to response is deprecated for django3

- CHANGES.txt
- setup.py
> :bookmark: release 2.2.6

- CHANGES.txt
- setup.py
This new version just renames WindTemplate to CourseStringTemplate.
A trivial change, but will require some code changes in locustempus and mediathread.
> :bookmark: Release version 2.3.0

- courseaffils/tests/test_columbia.py
- courseaffils/tests/test_views.py
> Use 'assertEqual' in tests
