CHANGES.txt, courseaffils/forms.py, courseaffils/tests/test_forms.py, setup.py
Removing an instructor from a course previously only removed them from the course's student group. Readding the user to the course automtically made them an instructor. The code now pulls an instructor from both the student and faculty groups.
Fixes PMT#101354
=> :bug Remove instructor

CHANGES.txt, courseaffils/columbia.py, courseaffils/forms.py, courseaffils/tests/test_columbia.py, setup.py
SW reported problems adding sections keys with leading letters (not digits) to care-ssw (aka carr).  I think this will likely affect our other apps too. Would be nice if we could learn about such changes in rules, but cest la vie. 
I added a test and changed the regex here, though after someone looks at this it probably needs to be redeployed to at least carr and medithread. Not sure what else.
=> SW course sections can now start with letters, not only digits

CHANGES.txt, courseaffils/admin.py, setup.py
The extra (and never used or displayed) search fields result in object duplication.
=> Remove extraneous search criteria from admin course list view.

courseaffils/views.py
Non-staff users shouldn't see all sandboxes, only the sandboxes
in the list of courses obtained through get_courses_for_user.
=> Fix sandbox courses for non-staff users

courseaffils/columbia.py, courseaffils/tests/test_columbia.py
I need to parse the affiliation string in Mediathread, and
in order to take advantage of the COURSEAFFILS_COURSESTRING_MAPPER
config setting (for installations outside columbia), this needs to be
available through the CourseStringMapper object.
=> Provide WindTemplate.to_dict through CourseStringMapper

courseaffils/middleware.py
This is necessary to replace CourseListView with a different view in
Mediathread, depending on a feature flag.
=> Allow CourseListView to be overridden

courseaffils/lib.py, courseaffils/models.py, courseaffils/tests/test_lib.py, courseaffils/tests/test_models.py, courseaffils/tests/test_utils.py, courseaffils/utils.py, courseaffils/views.py
For determining whether an affil belongs in Mediathread's past, present
or future courses table.
It's named kind of weird.. I'm open to suggestions.
=> Add Affil.past_present_future

courseaffils/models.py
CourseInfo has a `__str__` method that needs to be `__unicode__` on
python 2.
=> Add missing python_2_unicode_compatible decorator

CHANGES.txt, courseaffils/templates/courseaffils/course_list.html, courseaffils/tests/test_views.py, courseaffils/views.py
This removes the `infoless_courses` context variable. Sandbox courses
are no longer queried in each CourseListView request.
=> Add sandbox courses filter - PMT #107323

courseaffils/templates/courseaffils/course_row.html
Sandboxes have no term, which was causing a display issue in the
sandboxes tab.
=> Fix table display issue for courses with no term

courseaffils/forms.py, courseaffils/tests/test_forms.py
Addresses Sentry error:
https://sentry.ccnmtl.columbia.edu/sentry-internal/mediathread/group/922/
It looks like this boolean was flipped... maybe there was some confusion
because of the double negative:
if not 'course_string' not in self._errors:
I think what this piece of code is intending to do is initialize
`self._errors['course_string']` if it doesn't exist.
I added a test to go through this code path.
=> Fix error in CourseAdminForm.clean()

courseaffils/middleware.py, courseaffils/tests/test_middleware.py
On a set_course request, raise a 404 if the set_course parameter's value is not a valid group name. Resolves sentry #174722322
=> set_course: verify requested course is valid

courseaffils/middleware.py, courseaffils/models.py, courseaffils/tests/test_middleware.py, courseaffils/tests/test_models.py, test_reqs.txt
`request.REQUEST` was deprecated in 1.7 and removed in 1.9:
https://docs.djangoproject.com/en/1.8/ref/request-response/#django.http.HttpRequest.REQUEST
it used to just search `POST` first followed by `GET`, so just inline
that as the replacement.
=> replace request.REQUEST with POST and GET

.travis.yml
per instructions in the wiki here:
https://wiki.ctl.columbia.edu/index.php/PyPI_Release
this should allow TravisCI to build the sdist/wheel and upload them to
PyPI without any of us having to directly login and do it.
=> setup PyPI deployment from TravisCI

courseaffils/lib.py, courseaffils/middleware.py
* Replace Contexts with dicts
* The pattern of rendering a TemplateView within the middleware response breaks
in Django 1.11.1. The error is "ContentNotRenderedError.
The response content must be rendered before it can be accessed." Some
discussion of the issue is here: https://goo.gl/xrtyA4. The resolution is to
explicitly call "render" on a successful response before return.
=> Django 1.11.1 supporting changes

CHANGES.txt, courseaffils/middleware.py
https://docs.djangoproject.com/en/2.2/topics/http/middleware/#upgrading-pre-django-1-10-style-middleware
Resolves the following mediathread error with new ccnmtlsettings:
> TypeError: MethCourseManagerMiddleware() takes no arguments
=> middleware.py: inherit MiddlewareMixin

CHANGES.txt, courseaffils/columbia.py, setup.py
This error was uncovered by this change (8fbead49a7e732ce4c6dc3263231d6bb6b828255) that updated the bare except statement here.
HTTPError needs to be caught during mediathread unit testing, for urls like http://www.columbia.edu/cu/bulletin/uwb/subj/SCNC/F1000-20161-001/ that return a 404. In this case, `get_course_info()` should fail silently, returning no extra course info.
=> Catch HTTPError exception when getting extra course info

CHANGES.txt, courseaffils/lib.py, courseaffils/tests/test_lib.py
This fixes the following error that can occur if this function is called
on an AnonymousUser:
AttributeError: 'AnonymousUser' object has no attribute 'get_full_name'
=> Handle AnonymousUser in handle_public_name

CHANGES.txt, courseaffils/columbia.py, courseaffils/tests/test_columbia.py
WIND is deprecated, and the template format here isn't necessarily tied to the authentication scheme (now CAS). I think CourseStringTemplate makes more sense here.
=> Rename WindTemplate to CourseStringTemplate

.github/workflows/build-and-test.yml
4.2 is the LTS release that we'll be using for all our applications.
=> Test on django 4.2 instead of 4.1

courseaffils/templates/courseaffils/admin_change_form.html
In a Django 4.2 project with Courseaffils, there is an error stemming from this line when you try to add a course from the admin panel. This would just be commenting out the code but I'm not sure if there's an easy fix or if we can just get rid of that bit.
Error:
```
ValueError at /admin/courseaffils/course/add/
'Course' instance needs to have a primary key value before this relationship can be used.
```
=> ValueError fix
